<?php
return array(
    /*
     * Application ID generated by AppStore
     */
    'appId' => 'fcf0a2049bbb03d54976a8f7d84cf010',

    /*
     * Secret generated by AppStore
     */
    'appSecret' => '0ed75886469536f28cf3994ffd22c926a872fa56',

    /*
     * AppStore Secret generated by AppStore
     */
    'appstoreSecret' => 'e1a7dcfda370fce030ec026e24a141db82b4d2d1',


    'db' => array(
        /*
         * PDO DSN
         */
        'connection' => 'mysql:host=localhost;dbname=pirkspar_picturecategories',

        /*
         * PDO Database username
         */
        'user' => 'pirkspar_picturecategories',

        /*
         * PDO Database password
         */
        'pass' => 'KzQYi9mZP6Y6w'
    ),

    /*
     * Enable debug mode or not
     */
    'debug' => true,

    'appURL' => 'https://killerddd.pl/picture_categories/',

    /*
     * Path to log file or empty to disable logging
     */
    'logFile' => "logs/application.log",


    /*
     * timezone of the application
     *
     * Value is passed to date_default_timezone_set function
     */
    'timezone' => 'Europe/Warsaw',

    'php' => array(
        /*
         * This determines whether errors should be printed to the screen as
         * part of the output or if they should be hidden from the user
         *
         * Value is passed to ini_set function
         */
        'display_errors' => 'off'
    )
);
